2025-05-09 17:41:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-214]
2025-05-09 17:42:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-214]
2025-05-09 17:42:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-214]
2025-05-12 16:13:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-214]
2025-05-12 18:27:57 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO [*]user (email, password, name, role) VALUES (\000d\000a  'employee@test.com',\000d\000a  '$2a$10$7VFAzZqHnObevYwAdWmY2OfvO3EsZ6A3tuo9BEZef9RtP7ps73u3m', -- encoded 'password'\000d\000a  'Test Employee',\000d\000a  'employee'\000d\000a)"; expected "identifier"; SQL statement:
INSERT INTO user (email, password, name, role) VALUES (
  'employee@test.com',
  '$2a$10$7VFAzZqHnObevYwAdWmY2OfvO3EsZ6A3tuo9BEZef9RtP7ps73u3m', -- encoded 'password'
  'Test Employee',
  'employee'
) [42001-214]
2025-05-12 18:28:15 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO [*]user (email, password, name, role) VALUES (\000d\000a  'employee@test.com',\000d\000a  'password',\000d\000a  'Test Employee',\000d\000a  'employee'\000d\000a)"; expected "identifier"; SQL statement:
INSERT INTO user (email, password, name, role) VALUES (
  'employee@test.com',
  'password',
  'Test Employee',
  'employee'
) [42001-214]
2025-05-12 18:29:29 jdbc[14]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "user" not found; SQL statement:
INSERT INTO "user" (email, password, name, role) VALUES (
  'employee@test.com',
  '$2a$10$7VFAzZqHnObevYwAdWmY2OfvO3EsZ6A3tuo9BEZef9RtP7ps73u3m', -- encoded password: 'password'
  'Test Employee',
  'employee'
) [42102-214]
2025-05-12 18:44:15 jdbc[15]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-214]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:190)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:132)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:733)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:678)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 16 more
